### ISSUE TITLE
Service should warn against configurations with different brokers for commands and response

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/device-mqtt-go#158]
Version: v1.2.1

The current version of device-mqtt allows broker configuration to be specified independently for per-device commands (i.e. commands received from EdgeX) and globally for responses (which are received in response to the afore-mentioned commands). This doesn't make sense as if you send a command to a broker, it doesn't make sense that you'd be receiving the response from a different broker.

This issue is a suggestion that the service should error out if someone has used this configuration, or if this change is considered not backwards compatible, then the service should output a warning message. In that case, we should consider re-vamping the configuration of broker for the Ireland (2.0 release) instead.

See issue #89 for more details.

**Comment by iain-anderson** [comment]
Service should log an Error but carry on. For v2.0 the config should be simplified

**Comment by weichou1229** [comment]
Consider redesigning as below 

1. Move the clientId and topic to device json payload:
```
{
  "apiVersion": "v2",
  "device": {
    "name": "testDevice",
    ...
    "serviceName": "device-mqtt",
    "profileName": "profileA",
    "protocols": {
      "mqtt": {
        "incomingClientId": "IncomingDataSubscriber",
        "incomingTopic": "DataTopic",
        
        "commandClientId": "CommandPublisher",
        "commandTopic": "CommandTopic",
        "responseClientId": "CommandResponseSubscriber",
        "responseTopic": "ResponseTopic"
      }
    }
  }
}
```

2. device service only uses one MQTT broker info in the configuration.toml:
```
[MQTTBrokerInfo]
Schema = "tcp"
Host = "0.0.0.0"
Port = "1883"
Qos = 0
KeepAlive = 3600

CredentialsRetryTime = 120 # Seconds
CredentialsRetryWait = 1 # Seconds
ConnEstablishingRetry = 10
ConnRetryWaitTime = 5

AuthMode = 'usernamepassword'
CredentialsPath = 'credentials'
```

**Comment by cloudxxx8** [comment]
@tonyespy @lenny-intel @iain-anderson please help review whether this design is fine.

**Comment by iain-anderson** [comment]
LGTM

**Comment by tonyespy** [comment]
We just had a discussion about this issue in the WG meeting. @lenny-intel will follow-up with comments based on that discussion.

I also would like to make sure that we consider issue #89 as part of our upgrade to 2.x.

**Comment by lenny-intel** [comment]
@weichou1229 , @cloudxxx8 , we discussed this in today's WG meeting. Here is the feedback on the above approach.

1. Client ID is per connection, so need only one under `MqttBrokerInfo`
2. IncomingTopic doesn't need to be defined per Device. It is for async data from any device. The JSON wrapper currently used has the device and command information needed to create the event. Having it per device is redundant to the data in the JSON wrapper. This should be moved to `MqttBrokerInfo`. The topic `path` could be define more dynamic to eliminate the need for the JSON wrapper. i.e. `/data/{device}/{command}` with the `IncomingTopic` set to subscribe to `/data/#` and process info from received topic.
3. ResponseTopic doesn't need to be defined per Device. The data received on ResponseTopic has a UUID that was passed in the data published on Command topic. This should be moved to `MqttBrokerInfo` . Here we could also you the topic to specify the info in the response JSON wrapper, i.e. `/response/{uuid}`. Subscribe to `/response` and process info from received topic.
4. So should only have CommandTopic in protocols as this is very device specific. Here we could also use the topic to specify the info in the command JSON wrapper, i.e. publish to `/command/{command}/{uuid}` and device has to subscribe to `/command/{command}/#`  and pull the UUID from the received topic.

@tonyespy , @iain-anderson , FYI thoughts on using topic paths rather than JSON wrapper?

**Comment by cloudxxx8** [comment]
@lenny-intel use topic rather than JSON wrapper would be another issue and PR, because there will be lots of changes.
the major work here is to use a single broker.

**Comment by cloudxxx8** [comment]
we can achieve item 1, move Client ID to MqttBrokerInfo first

**Comment by weichou1229** [comment]
@lenny-intel @tonyespy 
I will do the following implementation:
- Move the clientId to `MQTTBrokerInfo`
- Create three persistent connections to solve the issue #89
- Modified the configuration to use a single broker 

The configuration.toml should be
```
[MQTTBrokerInfo]
Schema = "tcp"
Host = "0.0.0.0"
Port = "1883"
Qos = 0
KeepAlive = 3600

CredentialsRetryTime = 120 # Seconds
CredentialsRetryWait = 1 # Seconds
ConnEstablishingRetry = 10
ConnRetryWaitTime = 5

AuthMode = "usernamepassword"
CredentialsPath = "credentials"

IncomingClientId = "IncomingDataSubscriber"
CommandClientId = "CommandPublisher"
responseClientId = "CommandResponseSubscriber"

IncomingTopic = "DataTopic"
responseTopic = "ResponseTopic"
```
And the device json payload should be:
```
{
  "apiVersion": "v2",
  "device": {
    "name": "testDevice",
    ...
    "serviceName": "device-mqtt",
    "profileName": "profileA",
    "protocols": {
      "mqtt": {
        "commandTopic": "CommandTopic"
      }
    }
  }
}
```

> FYI thoughts on using topic paths rather than JSON wrapper?

Once the WG confirm the design, I can create another PR to make enhancement.

**Comment by lenny-intel** [comment]
> Move the clientId to `MQTTBrokerInfo` and create three persistent connections to solve the issue #89
> * GET or PUT: One connection to publish the request and one connection to subscribe the response
> * Async data: One connection to subscribe the async data

Why do we need multiple connections to the same broker? 
There should be one MQTT Client created on started-up using a single client ID. The different subscribe/publish topics all use the single connected client. 

Your new proposed config looks fine except the multiple client id's. Just need single client id for the single client.

**Comment by weichou1229** [comment]
No problem, I will try that.
