### ISSUE TITLE
How to change timeout value?

### ISSUE THREAD

**Issue by Haoyuli1990** [edgexfoundry/device-mqtt-go#214]
When I am going to get mqtt device parameters through the device API, my device does not return data in 5 seconds, and the API times out. 
How can I solve this problem?

For example, I curl http://127.0.0.1:48082/api/v1/device/name/owon/command/timezone , but timeout.

**Comment by weichou1229** [comment]
Could you use subscribe the message from the broker? It's more general for MQTT protocol.
https://docs.edgexfoundry.org/1.3/examples/Ch-ExamplesAddingMQTTDevice/#async-device-reading

Otherwise, it's need to modify the following code snippet to increase the loops or increase the sleep time.
```
	for i := 0; i < 5; i++ {
		cmdResponse, ok = d.CommandResponses.Load(cmdUuid)
		if ok {
			d.CommandResponses.Delete(cmdUuid)
			break
		} else {
			time.Sleep(time.Second * time.Duration(1))
		}
	}
```
https://github.com/edgexfoundry/device-mqtt-go/blob/master/internal/driver/driver.go#L454
